guestbook/urls.py
from django.conf.urls import url
from .views import index, message_post, message_table
from django.urls import re_path


app_name = 'guestbook'

urlpatterns = [
    re_path(r'^add_message', message_post, name='add_message'),
    url(r'^$', index, name='index'),
    url(r'result_table', message_table, name='result_table'),
]

lab_1/urls.py
from django.urls import re_path
from .views import index
#url for app
urlpatterns = [
    re_path(r'^$', index, name='index'),
]

lab_4/urls.py
from django.conf.urls import url
from .views import index

app_name = 'lab_4'
#url for app
urlpatterns = [
    url(r'^$', index, name='index'),
]

my_experience/urls.py
from django.urls import re_path
from .views import my_experience
#url for app
urlpatterns = [
    re_path(r'^my_experience/$', my_experience, name='my_experience'),
]

praktikum/urls.py
from django.conf.urls import include, url

from django.urls import re_path, path, include
from django.contrib import admin
from lab_1.views import index as index_lab1
from my_experience.views import my_experience
from guestbook.views import index as index_guestbook
import guestbook.urls as guestbook
from lab_4.views import index as index_lab4
from django.views.generic.base import TemplateView  # new


# Modul terakhir


from django.views.generic.base import RedirectView


urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^lab-1/', include('lab_1.urls')),
    re_path(r'^my_experience/', include('my_experience.urls')),
    re_path(r'^$', index_lab1, name='index'),
    re_path(r'^my_experience/$', my_experience, name='my_experience'),
    re_path(r'^guestbook/', include('guestbook.urls')),
    re_path(r'^guestbook/$', index_guestbook, name='guestbook'),
    url(r'^guestbook/', include(guestbook, namespace='guestbook')),
    re_path(r'^lab_4/', include('lab_4.urls')),
    re_path(r'^lab_4/$', index_lab4, name='lab_4'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('home', TemplateView.as_view(
        template_name='home.html'), name='home'),  # new


]

guestbook/models.py
from django.db import models

# Create your models here.
class Message(models.Model):
	name = models.CharField(max_length=27)
	email = models.EmailField()
	message = models.TextField()
	created_date = models.DateTimeField(auto_now_add=True)
	def str (self):
		return self.message

lab_1/models.py
from django.db import models

# Create your models here.

lab_4/models.py
from django.db import models

# Create your models here.

my_experience/models.py
from django.db import models

# Create your models here.

guestbook/forms.py
from django import forms


class Message_Form(forms.Form):
    error_messages = {
        'required': 'Tolong isi input ini',
        'invalid': 'Isi input dengan email',
    }
    attrs = {
        'class': 'form-control'
    }

    name = forms.CharField(label='Nama', required=False, max_length=27,
                           empty_value='Anonymous', widget=forms.TextInput(attrs=attrs))
    email = forms.EmailField(
        required=False, widget=forms.EmailInput(attrs=attrs))
    message = forms.CharField(
        widget=forms.Textarea(attrs=attrs), required=True)

guestbook/views.py
# Create your views here.
from django.shortcuts import render
from django.http import HttpResponseRedirect
from .forms import Message_Form
from .models import Message
from django.contrib.admin.views.decorators import staff_member_required

response = {'nama': "Nadhif"}


@staff_member_required
def index(request):
    response['message_form'] = Message_Form
    html = 'guestbook.html'
    return render(request, html, response)


def message_post(request):
    form = Message_Form(request.POST or None)
    if(request.method == 'POST' and form.is_valid()):
        response['name'] = request.POST['name'] if request.POST['name'] != "" else "Anonymous"
        response['email'] = request.POST['email'] if request.POST['email'] != "" else "Anonymous"
        response['message'] = request.POST['message']
        message = Message(name=response['name'], email=response['email'],
                          message=response['message'])
        message.save()
        html = 'form_result.html'
        return render(request, html, response)
    else:
        return HttpResponseRedirect('/')


def message_table(request):
    message = Message.objects.all()
    response['message'] = message
    html = 'table.html'
    return render(request, html, response)

lab_1/views.py
from django.shortcuts import render
from datetime import datetime, date
# Enter your name here
mhs_name = 'Nadhif' # TODO Implement this
curr_year = int(datetime.now().strftime("%Y"))
birth_date = date(1998,5,1) #TODO Implement this, format (Year, Month, Date)
npm = 200 # TODO Implement this
# Create your views here.
def index(request):
    response = {'name': mhs_name, 'age': calculate_age(birth_date.year), 'npm': npm}
    return render(request, 'index_lab1.html', response)

def calculate_age(birth_year):
    return curr_year - birth_year if birth_year <= curr_year else 0

lab_4/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    response = {}
    return render(request, 'lab_4/lab_4.html', response)

my_experience/views.py
from django.shortcuts import render

# Create your views here.


def my_experience(request):
    return render(request, 'my_experience.html')

guestbook/templates/form_result.html
{% extends "layout/base.html" %}
{% block title %} Pesan dari {{ name }} {% endblock %}
{% block content %}

<textarea readonly rows="5" class="form-control">&quot;{{message}}&quot;-
{{name}}
by {{ email }}
</textarea>
{% endblock %}
{% block footer %}
<p> &copy; {{name}} </p>
{% endblock %}

guestbook/templates/guestbook.html
{% extends "layout/base.html" %}
{% block content %}

<section name="form">
    <h2>Send Message</h2>

    {% if form.errors %}

    {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
        <strong>{{ error|escape }}</strong>
    </div>
    {% endfor %}
    {% endif %}


    <form id="form" method="POST" action="{% url 'guestbook:add_message' %}">
        {% csrf_token %}
        {{ message_form }}
        <br>
        <button type="submit" class="btn btn-default">Submit</button>
    </form>
</section>
{% endblock %}

guestbook/templates/layout/base.html
{% load staticfiles %}

<!DOCTYPE html>

<head>
	<meta charset="UTF-8">
	<title>MESSAGED BY : {{nama}}</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css"
		integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">

</head>

<title>
	{% block title %} {{nama}} GuestBook {% endblock %}
</title>

<body style="background-color: rgb(230, 230, 230)">
	{% include "partials/header.html" %}
	<div class="container">

		<div class="row mt-3">
			<div class="col-sm-1"></div>
			<div class="col-sm-10">
				{% block content %} {% endblock %}
			</div>
			<div class="col-sm-1"></div>
		</div>
	</div>

	{% block footer %}
	{% include "partials/footer.html" %}
	{% endblock %}
</body>

<!-- Jquery n Bootstrap Script -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script type="application/javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
</script>

guestbook/templates/partials/footer.html
<!-- Footer -->
<footer class="page-footer font-small blue">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">&copy; 2018 Copyright:
        <a href="#"> Sinar Nadhif Ilyasa</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

guestbook/templates/partials/header.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <title>GuestBook</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>




  <nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="navbar-collapse collapse w-100 order-1 order-md-0 dual-collapse2">
      <ul class="navbar-nav mr-auto">

        <li class="nav-item active"><a class="nav-link" href="{% url 'guestbook:index' %}">Send a Message </a></li>
        <li class="nav-item active"><a class="nav-link" href="{% url 'guestbook:result_table' %}">Table Message </a>
        </li>

      </ul>
    </div>
    <div class="mx-auto order-0">
      <a class="navbar-brand mx-auto" href="#">Guestbook</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".dual-collapse2">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse w-100 order-3 dual-collapse2">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'index' %}">Back to Profile</a>
        </li>
      </ul>
    </div>
  </nav>

  <!-- Awal Navbar -->

  <!-- <nav class="navbar navbar-expand-lg navbar-light bg-light">

    <a class="navbar-brand" href="#">GuestBook</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav">
        <li class="nav-item"><a class="nav-link" href="{% url 'guestbook:index' %}">Send a Message </a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'guestbook:result_table' %}">Table Message </a></li>



      </div>

    </div>
  </nav> -->

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous">
  </script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous">
  </script>

</body>

</html>

guestbook/templates/table.html
{% extends "layout/base.html" %}
{% block title %} Kumpulan Pesan {% endblock %}
{% block content %}
<!-- Populate semua isi pesan dari model -->
<table class="table">
    <thead>
        <th>Nama</th>
        <th>Email</th>
        <th>Pesan</th>
        <th>Dibuat Pada</th>
    </thead>
    <tbody>
        <!-- TODO, Kalau nama/email anon maka tr classnya jadi warning -->
        {% for i in message %}
        {% if i.name == 'Anonymous' or i.email == 'Anonymous' %}
        <tr class="warning"> {% else %}
        <tr class="success">
            {% endif %}
            <td> {{i.name}} </td>
            <td> {{i.email}} </td>
            <td> {{i.message}} </td>
            <td> {{i.created_date.time}} </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

lab_1/templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My Profile</title>

  <link rel="stylesheet" type="text/css" href="{% static 'lab_1/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Acme&display=swap" rel="stylesheet">
  <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"> -->


  <!-- Bootstrap core CSS -->
  <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->


  <link href="{% static 'lab_1/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>


  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-dark border-right pt-4" id="sidebar-wrapper">
      <div class="sidebar-heading text-white"><i class="fa fa-user-o" aria-hidden="true"></i> Profile </div>
      <div class="list-group list-group-flush">
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white mt-3">About Me</a>

        <a href="{% url 'index/my_experience' %}" class="list-group-item list-group-item-action bg-dark text-white">My
          Experience</a>

      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <!-- <div id="page-content-wrapper"> -->


    <div class="container">

      <div class="row">


        <div class="col-md-6 sm-6 xs-6">
          <img src="{% static 'lab_1/me.jpg' %}" alt="my image" width="400px" height="350px" class="img-thumbnail">
        </div>


        <div class="col-md-6 sm-6 xs-6">
          <h1>Sinar Nadhif Ilyasa</h1>
          <p class="text-dark">Saya Lahir di Sukoharjo, tanggal 30 Mei 1998. Sekarang tinggal dekat kota Solo,
            berprofesi
            sebagai Mahasiswa Informatika</p>

          <p><strong>Harapan :</strong></p>
          <div class="content">
            <p style="font-family: 'Acme', sans-serif; font-size:20px;">Belajar membuat website dengan Django
              Framework, semoga saya bisa mengaplikasikannya ke masyarakat supaya bermanfaat"
            </p>
          </div>

          <div class="sosmed">
            <p style="font-size: 15px; margin-top: 5px;">Follow my social media :
              <a href="https://www.facebook.com/StealthKid" class="fa fa-facebook"></a>
              <a href="https://twitter.com/Serpentz5" class="fa fa-twitter"></a>
              <a href="https://www.instagram.com/sinarnadhifilyasa/" class="fa fa-instagram"></a></p>

          </div>

        </div>

      </div>


      <!--   </div> -->


    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>



</body>

</html>

lab_1/templates/index_lab1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>My Profile</title>

  <link rel="stylesheet" type="text/css" href="{% static 'lab_1/style.css' %}">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Acme&display=swap" rel="stylesheet">
  <!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"> -->


  <!-- Bootstrap core CSS -->
  <!-- <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> -->


  <link href="{% static 'lab_1/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>


  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-dark border-right pt-4" id="sidebar-wrapper">
      <div class="sidebar-heading text-white"><i class="fa fa-user-o" aria-hidden="true"></i> Profile </div>
      <div class="list-group list-group-flush">
        <a href="#" class="list-group-item list-group-item-action bg-dark text-white mt-3">About Me</a>

        <a href="{% url 'my_experience' %}" class="list-group-item list-group-item-action bg-dark text-white">My
          Experience</a>
        <a href="{% url 'guestbook' %}" class="list-group-item list-group-item-action bg-dark text-white">Guestbook</a>
        <a href="{% url 'lab_4' %}" class="list-group-item list-group-item-action bg-dark text-white">Chatbox</a>

        {% block content %}

        {% if user.is_authenticated %}
        <a href="{% url 'logout' %}" class="list-group-item list-group-item-action bg-dark text-white">Logout</a>

        <!-- Hi {{ user.username }}! -->

        {% else %}
        <a href="{% url 'login' %}" class="list-group-item list-group-item-action bg-dark text-white">Login</a>


        {% endif %}
        {% endblock %}


      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <!-- <div id="page-content-wrapper"> -->


    <div class="container">

      <div class="row">


        <div class="col-md-6 sm-6 xs-6">
          <img src="{% static 'lab_1/me.jpg' %}" alt="my image" width="400px" height="350px" class="img-thumbnail">
        </div>


        <div class="col-md-6 sm-6 xs-6">
          <h1>Sinar Nadhif Ilyasa</h1>
          <p class="text-dark">Saya Lahir di Sukoharjo, tanggal 30 Mei 1998. Sekarang tinggal dekat kota Solo,
            berprofesi
            sebagai Mahasiswa Informatika</p>

          <p><strong>Harapan :</strong></p>
          <div class="content">
            <p style="font-family: 'Acme', sans-serif; font-size:20px;">Belajar membuat website dengan Django
              Framework, semoga saya bisa mengaplikasikannya ke masyarakat supaya bermanfaat"
            </p>
          </div>

          <div class="sosmed">
            <p style="font-size: 15px; margin-top: 5px;">Follow my social media :
              <a href="https://www.facebook.com/StealthKid" class="fa fa-facebook"></a>
              <a href="https://twitter.com/Serpentz5" class="fa fa-twitter"></a>
              <a href="https://www.instagram.com/sinarnadhifilyasa/" class="fa fa-instagram"></a></p>

          </div>

        </div>

      </div>


      <!--   </div> -->


    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="vendor/jquery/jquery.min.js"></script>
  <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>



</body>

</html>

lab_1/templates/index_lab2.html
{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">
    <title>{{ name }}</title>
    <link rel="stylesheet" type="text/css" href="{% static 'lab_1/style.css' %}">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Acme&display=swap" rel="stylesheet">
</head>

<body>

    <div class="container">
        <div class="row">


            <div class="col-md-6 sm-6 xs-6">
                <img src="{% static 'lab_1/me.jpg' %}" alt="my image" width="400px" height="350px"
                    class="img-thumbnail">
            </div>


            <div class="col-md-6 sm-6 xs-6">
                <h1>Sinar Nadhif Ilyasa</h1>
                <p style="color:grey">Saya Lahir di Sukoharjo, tanggal 30 Mei 1998. Sekarang tinggal dekat kota Solo,
                    berprofesi
                    sebagai Mahasiswa Informatika</p>

                <p><strong>Harapan :</strong></p>
                <div class="content">
                    <p style="font-family: 'Acme', sans-serif; font-size:20px;">Belajar membuat website dengan Django
                        Framework, semoga saya bisa mengaplikasikannya ke masyarakat supaya bermanfaat"
                    </p>
                </div>

                <div class="sosmed">
                    <p style="font-size: 15px; margin-top: 5px;">Follow my social media :
                        <a href="https://www.facebook.com/StealthKid" class="fa fa-facebook"></a>
                        <a href="https://twitter.com/Serpentz5" class="fa fa-twitter"></a>
                        <a href="https://www.instagram.com/sinarnadhifilyasa/" class="fa fa-instagram"></a></p>

                </div>

            </div>

        </div>


    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.min.js"
        integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"> </script>
    <!--  $(document).ready(function () {
        //     $('div.container').fadeIn(2200);
        //     // OR $('div.toshow').show(2200);
        //     // OR $('div.toshow').slideDown("slow");
        // });
    -->


    <!-- <h1>Hello my name is {{ name }}</h1>
    <article>NPM : {{ npm }}</article>
    <article>I am {{ age }} years old</article> -->
</body>

</html>

lab_4/templates/lab_4/lab_4.html
{% extends "lab_4/layout/base.html" %}
{% block content %}
<!-- ChatBox Section -->
<section name="Chatbox">
    <div class="wrapper">
        <div class="chat-box">
            <div class="chat-head">
                <h2>Chat</h2>
                <img src="https://maxcdn.icons8.com/windows10/PNG/16/Arrows/angle_down-16.png" title="Expand Arrow"
                    width="16">
            </div>
            <div class="chat-body">
                <div class="msg-insert">
                </div>
                <div class="chat-text">
                    <textarea placeholder="Press Enter"></textarea>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

lab_4/templates/lab_4/layout/base.html
{% load staticfiles %}
<!-- {% load static %} -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <meta name="author" content="{{author}}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.
css" rel="stylesheet" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js"></script>
    <!-- bootstrap csss -->
    <link href="//netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/lab_4.css' %}" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Droid+Sans:400,700">

    <title>
        Lab 4
    </title>
</head>

<body>
    <header>
        {% include "lab_4/partials/header.html" %}
    </header>

    <!-- Themes -->
    <div class="container">
        <h1 class="text-center">Select Tutorial</h1>
        <select style="width: 200px;" class="my-select">


        </select>
        <br /><button class="btn apply-button">Change Theme</button>
    </div>

    <content>
        {% block content %}
        <!-- content goes here -->
        {% endblock %}
    </content>
    <footer>
        <!-- TODO Block Footer dan include footer.html -->
        {% block footer %}
        {% include "lab_4/partials/footer.html" %}
        {% endblock %}
    </footer>
    <!-- Jquery n Bootstrap Script -->

    <script type="application/Javascript" src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js">
    </script>
    <script src="{% static 'js/lab_4.js' %}"></script>

    <script>
        $(document).ready(function () {
            $('.my-select').select2({
                data: JSON.parse(localStorage.themes)
            });

            $('.apply-button').on('click', function () {
                theme = themes[$('.my-select').val()];
                changeTheme(theme);
                localStorage.setItem('selectedTheme', JSON.stringify(theme));
            })

        });
    </script>





</body>

lab_4/templates/lab_4/partials/footer.html
<!-- Footer -->
<footer class="page-footer font-small blue">

    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">&copy; 2019 Copyright:
        <a href="#"> Sinar Nadhif Ilyasa</a>
    </div>
    <!-- Copyright -->

</footer>
<!-- Footer -->

lab_4/templates/lab_4/partials/header.html
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <a class="navbar-brand" href="#">Chatbox</a>
        </div>

        <ul class="nav navbar-nav navbar-right">
            <li class="nav-item active">
                <a class="nav-link" href="{% url 'index' %}">Back to Profile</a>
            </li>
        </ul>
    </div>
</nav>

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title>{% block title %}Django Auth Tutorial{% endblock %}</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <style type="text/css">
    .login-form {
      width: 340px;
      margin: 50px auto;
      padding-top: 100px;
    }

    .login-form form {
      margin-bottom: 15px;
      background: #f7f7f7;
      box-shadow: 0px 2px 2px rgba(0, 0, 0, 0.3);
      padding: 30px;
    }

    .login-form h2 {
      margin: 0 0 15px;
    }

    .form-control,
    .btn {
      min-height: 38px;
      border-radius: 2px;
    }

    .btn {
      font-size: 15px;
      font-weight: bold;
    }
  </style>
</head>

<body>
  <main>
    {% block content %}
    {% endblock %}

  </main>
</body>

</html>

templates/description_lab2addon.html
{% extends "base.html" %}
{% block content %}
<h3 style="text-align: center">Hi all, This is my complete biodata</h3>
<table align="center" style="text-align: center">
    {% for bio in bio_dict %}
        <tr>
            <td class="subject">{{ bio.subject }}</td>
            <td class="value">{{ bio.value }}</td>
        </tr>
    {% endfor %}
</table>
<br><br>
{% endblock %}